// swift-tools-version: 5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "Features",
    platforms: [
        .macOS(.v11),
    ],
    dependencies: [
        .package(path: "../Core"),
        .package(url: "https://github.com/johnsundell/files.git", from: "4.0.0"),
        // Make command plug-in available
        .package(path: "../../")
    ]
)

// Code between this separator and the next is autogenerated; do not edit
// MARK: - Autogenerated

var generatedProducts: [Product] = [
    .library(name: "Bar", targets: ["Bar"]),
    .library(name: "Common", targets: ["Common"]),
    .library(name: "Foo", targets: ["Foo"])
]

var generatedTargets: [Target] = [
    .target(
        name: "Bar",
        dependencies: [
            "Foo"
        ]
    ),
    .target(
        name: "Common",
        dependencies: [
            "Core",
            .product(name: "Files", package: "Files")
        ]
    ),
    .target(
        name: "Foo",
        dependencies: [
            "Common"
        ]
    ),
    .testTarget(
        name: "FeaturesTests",
        dependencies: [
            "Bar",
            "Common",
            "Foo"
        ]
    )
]

// Code below this separator may be edited
// MARK: End Autogenerated -

package.products += generatedProducts
package.targets += generatedTargets