//
//  ManifestHandlerTests.swift
//  PackageManifestGenerator
//
//  Created by Mathew Gacy on 2/2/24.
//

@testable import PackageManifestGeneratorCore
import Foundation
import XCTest

final class ManifestHandlerTests: XCTestCase {
    let sut = ManifestHandler.self
}

// MARK: - Components
extension ManifestHandlerTests {
    func testComponents() throws {
        let expectedPrefix = """
            let package = Package(name: "MyPackage")
            """
        let expectedSuffix = "suffix"

        let manifest = """
            let package = Package(name: "MyPackage")

            // Code between this separator and the next is autogenerated; do not edit
            // MARK: - Autogenerated

            generated

            // Code below this separator may be edited
            // MARK: End Autogenerated -

            suffix
            """
        let (actualPrefix, actualSuffix) = try sut.components(of: manifest)

        XCTAssertEqual(actualPrefix, expectedPrefix)
        XCTAssertEqual(actualSuffix, expectedSuffix)
    }

    func testComponentsOfUngeneratedManifest() throws {
        let manifest = """
            // swift-tools-version: 5.9
            // The swift-tools-version declares the minimum version of Swift required to build this package.

            import PackageDescription

            let package = Package(
                name: "Features",
                platforms: [
                    .macOS(.v11),
                ],
                products: [
                    .library(name: "Common", targets: ["Common"]),
                    .library(name: "Foo", targets: ["Foo"])
                ]
                dependencies: [
                    .package(path: "../Core"),
                ],
                targets: [
                    .target(
                      name: "Common",
                      dependencies: [
                        "Core",
                      ],
                    ),
                    .target(
                      name: "Foo",
                      dependencies: [
                        "Common"
                      ]
                    )
                ]
            )
            """

        let (actualPrefix, actualSuffix) = try sut.components(of: manifest)

        XCTAssertEqual(actualPrefix, manifest)
        XCTAssertNil(actualSuffix)
    }

    func testComponentsWithoutPackage() throws {
        let manifest = """
            let foo = "bar
            """

        XCTAssertThrows(
            try self.sut.components(of: manifest),
            "Missing declaration of `Package` instance named `package`")
    }

    func testComponentsOfInvalidManifest() throws {
        let manifest = """
            let package = Package(name: "MyPackage")

            // Code between this separator and the next is autogenerated; do not edit
            // MARK: - Autogenerated

            generated
            """

        XCTAssertThrows(
            try self.sut.components(of: manifest),
            "Invalid manifest")
    }
}

// MARK: - Assemble
extension ManifestHandlerTests {
    func testAssembleWithSuffix() throws {
        let expected = """
            prefix

            // Code between this separator and the next is autogenerated; do not edit
            // MARK: - Autogenerated

            generated

            // Code below this separator may be edited
            // MARK: End Autogenerated -

            suffix
            """

        let prefix = "prefix"
        let generated = "generated"
        let suffix = "suffix"
        let actual = sut.assemble(prefix: prefix, generated: generated, suffix: suffix)

        XCTAssertEqual(actual, expected)
    }

    func testAssembleWithoutSuffix() throws {
        let expected = """
            prefix

            // Code between this separator and the next is autogenerated; do not edit
            // MARK: - Autogenerated

            generated

            // Code below this separator may be edited
            // MARK: End Autogenerated -

            package.products += generatedProducts
            package.targets += generatedTargets
            """

        let prefix = "prefix"
        let generated = "generated"
        let actual = sut.assemble(prefix: prefix, generated: generated)

        XCTAssertEqual(actual, expected)
    }
}
